### ISSUE TITLE
make parser development plan

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/WaterSystems.jl#4]

**Comment by jdlara-berkeley** [comment]
I thought we had a plan *.ipnb -> wntr -> WaterSystems.jl.

**Comment by claytonpbarrows** [comment]
I think that's appropriate. @AmandaMason23 is enabling the *.inp -> Julia.pycall -> wntr -> WaterSystems.jl workflow now. I don't see much of a need for alternatives since I've never seen water data in any other format than *.inp.
